---
   - name: 1.Downloding the maven tar file and unarchive
     unarchive:
        src: "http://www.apache.org/dist/maven/maven-{{ maven_major }}/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
        dest: "{{ maven_home_parent_directory }}"
        copy: no

   - name: 3.Renaming the maven unzip folder.
     command: cp -r {{ maven_home_parent_directory }}/apache-maven-{{ maven_major }}/{{ maven_version }} /opt/maven

   - name: 4.Setting path for maven
     copy: content="export M2_HOME=/opt/maven export PATH=${M2_HOME}/bin:${PATH}" dest=/etc/profile

   - name: 5.Source the /etc/profile
     shell: "source /etc/profile"
